# Don't print a new line at the start of the prompt
add_newline = false

[aws]
format = "on [$symbol$profile( $region)]($style) "
style = "bold Yellow"
symbol = "â˜ï¸ "

[aws.region_aliases]
af-south-1 = "Cape Town"
ap-east-1 = "Hong Kong"
ap-northeast-1 = "Tokyo"
ap-northeast-2 = "Seoul"
ap-northeast-3 = "Osaka"
ap-south-1 = "Mumbai"
ap-southeast-1 = "Singapore"
ap-southeast-2 = "Sydney"
ca-central-1 = "Canada"
eu-central-1 = "Frankfurt"
eu-north-1 = "Stockholm"
eu-south-1 = "Milan"
eu-west-1 = "Ireland"
eu-west-2 = "London"
eu-west-3 = "Paris"
me-south-1 = "Bahrain"
sa-east-1 = "SÃ£o Paulo"
us-east-1 = "N. Virginia"
us-east-2 = "Ohio"
us-west-1 = "N. California"
us-west-2 = "Oregon"

[username]
disabled = false
show_always = true
style_root = "bold green"
style_user = "bold green"

[character]
success_symbol = 'ğŸ¦‘ â¯(bold black)'
error_symbol = "ğŸ”¥ â¯(bold red)"

[cmd_duration]
min_time = 500

[directory]
truncation_length = 5
truncate_to_repo = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[kubernetes]
symbol = "ï´± "
format = 'on [ï´± $context \($namespace\)](bold bright-green) '
disabled = false

[kubernetes.context_aliases]
"default" = "home-cluster"

[shell]
fish_indicator = "ğŸ¦ˆ"
bash_indicator = "ğŸŒ"
disabled = false
